services:
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    command:
      - postgres
      - -c
      - max_connections=1000
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evolution-net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: EMAIL
      PGADMIN_DEFAULT_PASSWORD: PASSWORD
    ports:
      - "4000:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - evolution-net

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    command: redis-server --port 6379 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - evolution_redis:/data
    networks:
      - evolution-net

  evolution-api:
    container_name: evolution_api_test
    image: evoapicloud/evolution-api:v2.1.1
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net

volumes:
  postgres_data:
  pgadmin_data:
  evolution_redis:
  evolution_instances:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
  
